[pytest]
testpaths = automation_framework/tests


addopts =
    -v
    --html=automation_framework/reports/report.html
    --self-contained-html



markers = 
    smoke: Smoke test cases
    regression: Regression test cases
    ui: UI test cases
    api: API automation tests
    database: Database validation tests
    integration: UI + API + Database integration tests
